# Generated by Django 3.2.2 on 2022-08-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechaland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
