# Generated by Django 3.2.2 on 2022-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechaland', '0003_alter_heroimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcheck',
            name='image',
            field=models.FileField(blank=True, upload_to='back-end-image/InterestCheck/'),
        ),
    ]
